### ISSUE TITLE
No export for unknown users

### ISSUE THREAD

**Issue by cracker0dks** [attituding/export-ms-teams-chats#2]
Thanks for your work. Works creat but it does not export chats for "unknown user"
![image](https://github.com/attituding/export-ms-teams-chats/assets/1816621/d7bf8e51-45a8-4a18-9c8a-061cd111c5c4)
This user was removed from azure (and teams) but the chat is still there.
Sadly it will not be exported.
Is there a solution to this?
Thanks :)

**Comment by attituding** [comment]
hey!

sorry for the very long delay in response, i had my notifications misconfigured. i hope the following response is still useful.

i just tested the scenario you described by creating a user, messaging them through teams, deleting the user, and trying to export. i find that when it attempts to export the chat with the new user, there are no messages and it doesn't show the name properly. i've created and committed a patch which resolves the behavior i saw.

once again, apologies for the very late response

**Comment by cracker0dks** [comment]
cant check if this works (Chat is gone), but I hope it will so I close this one.
Thanks a lot anyway :)
