### ISSUE TITLE
Export a specific chat

### ISSUE THREAD

**Issue by surisou** [attituding/export-ms-teams-chats#3]
Hi! This works great, but I was wondering if you knew how to have it look for and export one specific group chat by name instead of going through all chats I've ever been in. @attituding

**Comment by attituding** [comment]
hey!

i've just pushed an update that includes the option to speicify one or more chats.
unfortunately, you'll need to use the "legacy" method described in step 2 (https://github.com/attituding/export-ms-teams-chats?tab=readme-ov-file#2-run-the-script) to run the script as i don't have it working with the iex thing.

heres an example of its usage:
`./Get-MicrosoftTeamsChat.ps1 -toExport my-awesome-group-chat,"Person 1"`
^ that'll export chats it finds with the exact names `my-awesome-group-chat` and `Person 1`

lmk if you run into any issues, hopefully this is good enough for you

**Comment by surisou** [comment]
hi @attituding thank you so much for the quick response, I appreciate it.

I tried the legacy method and it doesn't get past the `./Get-MicrosoftTeamsChat.ps1` step - I tried this first before specifying the group chat. I did the other debugging steps as well like Set-ExecutionPolicy and running verbose mode and using PowerShell 7...No luck

The iex thing does work in exporting my chats but once it gets to the specific chat I want it doesn't work. It's 5 years worth of messages though so maybe it's too large?
![image](https://github.com/attituding/export-ms-teams-chats/assets/61033746/847a7c4d-f8bf-4fc7-ba68-66748693e714)

**Comment by attituding** [comment]
> I tried the legacy method and it doesn't get past the ./Get-MicrosoftTeamsChat.ps1 step - I tried this first before specifying the group chat. I did the other debugging steps as well like Set-ExecutionPolicy and running verbose mode and using PowerShell 7...No luck

What error did you get exactly?

> The iex thing does work in exporting my chats but once it gets to the specific chat I want it doesn't work. It's 5 years worth of messages though so maybe it's too large?

I've just pushed a an update that adds a tiny bit more verbose output. If you're fine with it, could you try running it again (with iex) with verbose output on and send the output (with appropriate redaction)?
```
irm https://attituding.github.io/export-ms-teams-chats/ps-verbose.ps1 | iex
```
If I had to guess, there might be a bug in trying to get a new access token. How long was the script running for before erroring?

**Comment by surisou** [comment]
> What error did you get exactly?
<img width="566" alt="image" src="https://github.com/attituding/export-ms-teams-chats/assets/61033746/d4a298f6-3a4a-454d-abef-e3e9ffabcc3f">
<img width="569" alt="image" src="https://github.com/attituding/export-ms-teams-chats/assets/61033746/65149d9d-3ca2-4625-a9b1-d0d97b75b3b2">

> I've just pushed a an update that adds a tiny bit more verbose output. If you're fine with it, could you try running it again (with iex) with verbose output on and send the output (with appropriate redaction)?

I'm running this now, started around 9am EST. Around 11:20am it started processing chat #888 of 895 and it is still going as I'm typing this. I'm assuming this is the Big chat that I need. Once in a while it will show the messages in the screenshot below but I haven't stopped it yet in case it just needs more time to finish
![image](https://github.com/attituding/export-ms-teams-chats/assets/61033746/7048db25-852d-4c49-ac3a-d0fbf36eccc6)
